[package]
name = "fasttext-serving"
version = "0.1.1"
authors = ["Messense Lv <messense@icloud.com>"]
description = "fastText model serving API server"
license = "MIT"
readme = "README.md"

[package.metadata.deb]
maintainer = "Messense Lv <messense@icloud.com>"
copyright = "2018, Messense Lv. <messense@icloud.com>"
license-file = ["LICENSE", "3"]
extended-description = "fastText model serving API server"
depends = "$auto"
section = "text"
priority = "optional"
assets = [
    # binary
    ["target/release/fasttext-serving", "usr/bin/", "755"],
]

[dependencies]
# rocket = "0.3"
# rocket_codegen = "0.3"
# rocket_contrib = "0.3"
rocket = { git = "https://github.com/messense/Rocket.git", branch = "v0.3" }
rocket_codegen = { git = "https://github.com/messense/Rocket.git", branch = "v0.3" }
rocket_contrib = { git = "https://github.com/messense/Rocket.git", branch = "v0.3" }
fasttext = { git = "https://github.com/messense/fasttext-rs.git" }
serde_json = "1.0"
clap = "2.29"
rayon = "0.9"

[profile.release]
lto = true
debug = true
