[package]
name = "fasttext-serving"
version = "0.2.8"
authors = ["Messense Lv <messense@icloud.com>"]
description = "fastText model serving API server"
license = "MIT"
readme = "README.md"
repository = "https://github.com/messense/fasttext-serving.git"

[package.metadata.deb]
maintainer = "Messense Lv <messense@icloud.com>"
copyright = "2018, Messense Lv. <messense@icloud.com>"
license-file = ["LICENSE", "3"]
extended-description = "fastText model serving API server"
depends = "$auto"
section = "text"
priority = "optional"
assets = [
    # binary
    ["target/release/fasttext-serving", "usr/bin/", "755"],
]

[dependencies]
rocket = "0.4.0-rc.2"
rocket_contrib = { version = "0.4.0-rc.2", default-features = false, features = ["json"] }
fasttext = "0.3"
clap = "2.30"
rayon = "1.0"

[profile.release]
lto = true
debug = true
